apiVersion: v1
kind: Service
metadata:
  name: image-caption-frontend
spec:
  type: NodePort
  selector:
    app: image-caption-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
